# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_pb2 as worker__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Worker Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/worker.WorkerService/RegisterWorker',
                request_serializer=worker__pb2.RegisterRequest.SerializeToString,
                response_deserializer=worker__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/worker.WorkerService/SendHeartbeat',
                request_serializer=worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SendLogs = channel.stream_unary(
                '/worker.WorkerService/SendLogs',
                request_serializer=worker__pb2.LogEntry.SerializeToString,
                response_deserializer=worker__pb2.SendLogsResponse.FromString,
                _registered_method=True)
        self.SendMetrics = channel.stream_unary(
                '/worker.WorkerService/SendMetrics',
                request_serializer=worker__pb2.MetricEntry.SerializeToString,
                response_deserializer=worker__pb2.SendMetricsResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/worker.WorkerService/GetConfig',
                request_serializer=worker__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=worker__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/worker.WorkerService/HealthCheck',
                request_serializer=worker__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=worker__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Communicate = channel.stream_stream(
                '/worker.WorkerService/Communicate',
                request_serializer=worker__pb2.WorkerMessage.SerializeToString,
                response_deserializer=worker__pb2.MasterMessage.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Worker Service definition
    """

    def RegisterWorker(self, request, context):
        """Register a worker with the master
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Send heartbeat from worker to master
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogs(self, request_iterator, context):
        """Send logs from worker to master (client streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMetrics(self, request_iterator, context):
        """Send metrics from worker to master (client streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Get configuration from master
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Communicate(self, request_iterator, context):
        """Bidirectional streaming for real-time communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=worker__pb2.RegisterRequest.FromString,
                    response_serializer=worker__pb2.RegisterResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SendLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.SendLogs,
                    request_deserializer=worker__pb2.LogEntry.FromString,
                    response_serializer=worker__pb2.SendLogsResponse.SerializeToString,
            ),
            'SendMetrics': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMetrics,
                    request_deserializer=worker__pb2.MetricEntry.FromString,
                    response_serializer=worker__pb2.SendMetricsResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=worker__pb2.GetConfigRequest.FromString,
                    response_serializer=worker__pb2.GetConfigResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=worker__pb2.HealthCheckRequest.FromString,
                    response_serializer=worker__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Communicate': grpc.stream_stream_rpc_method_handler(
                    servicer.Communicate,
                    request_deserializer=worker__pb2.WorkerMessage.FromString,
                    response_serializer=worker__pb2.MasterMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Worker Service definition
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/RegisterWorker',
            worker__pb2.RegisterRequest.SerializeToString,
            worker__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/SendHeartbeat',
            worker__pb2.HeartbeatRequest.SerializeToString,
            worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/worker.WorkerService/SendLogs',
            worker__pb2.LogEntry.SerializeToString,
            worker__pb2.SendLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/worker.WorkerService/SendMetrics',
            worker__pb2.MetricEntry.SerializeToString,
            worker__pb2.SendMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/GetConfig',
            worker__pb2.GetConfigRequest.SerializeToString,
            worker__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.WorkerService/HealthCheck',
            worker__pb2.HealthCheckRequest.SerializeToString,
            worker__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Communicate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/worker.WorkerService/Communicate',
            worker__pb2.WorkerMessage.SerializeToString,
            worker__pb2.MasterMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
